---
- name: "Copy SAMBA SSL certificate to Keycloak Server"
  shell:
    cmd: "openssl s_client -connect 10.0.2.4:636 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > sambaCert.pem"