---
- name: "Copy SSL certificates to server"
  include_tasks: addCerts.yml
  
- name: "Get SAMBA SSL certificate to Server"
  include_tasks: getSambaCertificate.yml

- name: "Copy theme files to server"
  include_tasks: addTheme.yml

- name: "Deploy keycloak_app & postgres_db containers"
  include_tasks: deployKeycloakContainer.yml

- name: "Create DIINF realm on Keycloak"
  include_tasks: realmConfig.yml