---
- name: "Clone Keycloak theme repository"
  ansible.builtin.git:
    repo: "{{ keycloak_theme_repository }}"
    dest: "{{ files_path }}"
  tags:
    - keycloak
    - theme_update

- name: "Copy docker-compose file to server"
  template:
    src: docker-compose.j2
    dest: "{{ files_path  }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - keycloak

- name: "Deploy {{ keycloak_container_name }} & {{ postgres_container_name }} containers with Docker-Compose"
  shell:
    cmd: "docker-compose -f {{ files_path }}/docker-compose.yml up -d"
  tags:
    - keycloak

- name: "Wait for Keycloak to get ready"
  wait_for:
    host: "{{ keycloak_server_ip }}"
    port: "{{ keycloak_container_port }}"
  tags:
    - keycloak