---
all:
  children:

    directoryService:     # Group
      hosts:
        samba.diinf.lan:  # Name, IP or FQDN

    authService:            # Group
      hosts:
        keycloak.diinf.tk:  # Name, IP or FQDN