---
all:
  children:

    directoryServer:  # Group
      hosts:
        samba.diinf.lan:            # FQDN
          ansible_host: 10.0.2.4    # Server IP

    authServer:       # Group
      hosts:
        keycloak.diinf.tk:          # FQDN
          ansible_host: 10.0.2.5    # Server IP