---
- hosts: all
  tags:
    - packages
  become: true
  roles:
    - common
    - docker
    - dockerCompose

- hosts: directoryServers
  tags:
    - directory
  become: true
  roles:
    - samba

- hosts: authServers
  tags:
    - authentication
  become: true
  roles:
    - keycloak
    - keycloakConfig