---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      name: docker.io=20.10.2-0ubuntu1~20.04.3
      state: present