---

- hosts: gcp
  become: true
  tasks:

  - name: Uninstall old Docker versions
    apt:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
      update_cache: yes

  - name: Install Docker packages
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
      state: present
      update_cache: yes
  
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Set up the stable repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install Docker engine
    apt:
      name:
        - docker-ce=5:20.10.7~3-0~ubuntu-focal
        - docker-ce-cli=5:20.10.7~3-0~ubuntu-focal
        - containerd.io=1.4.9-1
      state: present
      update_cache: yes

  - name: Unmask, start and enable Docker service
    systemd:
      name: docker
      masked: no
      state: started
      enabled: yes

  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'a+x'

  - name: Copy docker-compose to server
    copy:
      src: docker-compose.yml
      dest: ~/docker-compose.yml
      owner: root
      group: root
      mode: 0644