---
- hosts: all
  become: true
  roles:
    - common
    - docker
    - dockerCompose
    - pip

- hosts: directoryServers
  become: true
  roles:
    - samba

- hosts: authServers
  become: true
  roles:
    - keycloak
    - keycloakConfig