---
- hosts: all
  tags:
    - setup
  become: true
  roles:
    - common
    - docker
    - dockerCompose

- hosts: directoryServer
  tags:
    - directory
  become: true
  roles:
    - samba

- hosts: authServer
  tags:
    - authentication
  become: true
  roles:
    - keycloak
    - keycloakConfig