---
- hosts: all
  become: true
  roles:
    - common

- hosts: directoryServers
  become: true
  roles:
    - sambaServer

- hosts: authServers
  become: true
  roles:
    - keycloakServer
    - keycloakConfig