---
- hosts: all
  become: true
  tags:
    - basic_setup
    - samba_setup
    - keycloak_setup
  roles:
    - common
    - docker
    - dockerCompose
  vars_files:
    - vars.yml

- hosts: directoryServer
  become: true
  tags:
    - samba_setup
  roles:
    - samba
  vars_files:
    - vars.yml

- hosts: authServer
  become: true
  tags:
    - keycloak_setup
  roles:
    - keycloak
    - keycloakConfig
  vars_files:
    - vars.yml