---
# start file
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index
    apt:
      update_cache: yes
    changed_when: false
  
- hosts: keycloak
  become: true
  roles:
    - keycloak
  