---
- name: "Install Docker" 
  include_tasks: docker-install.yml

- name: "Install Docker-Compose"
  include_tasks: docker-compose-install.yml

- name: "Copy docker-compose.yml"
  include_tasks: copy-files.yml
  
- name: "Deploy Keycloak Container"
  shell:
    cmd: "docker-compose up -d"