---
# --- Toggles ---
enable_federation: true        # Turns ON or OFF the federation configuration on Keycloak
enable_identity_provider: true # Turns ON or OFF the identity provider configuration on Keycloak

# ----- Global -----
# Server IP
samba_server_ip: 10.0.2.4
keycloak_server_ip: 10.0.2.5

# Server FQDN
samba_server_fqdn: samba.diinf.lan
keycloak_server_fqdn: keycloak.diinf.tk

# Files
files_path: /opt/sistema-centralizado

# ----- Keycloak Service -----
# Container configuration
keycloak_container_name: keycloak-app
keycloak_container_port: 443

# Keycloak configuration
keycloak_admin_user: admin
keycloak_admin_password: Diinf1*

# URL
keycloak_base_url: "https://{{ keycloak_server_fqdn }}"

# Realm
keycloak_realm_name: DIINF

# Theme
keycloak_theme_name: DIINF
keycloak_theme_repository: https://github.com/RobertoLillo/Tema-DIINF-Keycloak
