---
- name: "Copy docker-compose file to server"
  template:
    src: docker-compose.j2
    dest: "{{ files_path  }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags: 
    - samba

- name: "Deploy {{ samba_container_name }} container with Docker-Compose"
  shell:
    cmd: "docker-compose -f {{ files_path  }}/docker-compose.yml up -d"
  tags: 
    - samba

- name: "Wait for Samba Service to open port 636"
  wait_for:
    host: "{{ samba_server_ip }}"
    port: 636
  tags: 
    - samba
