---
- name: "Copy certs files"
  copy:
    src: certs
    dest: /home/robert
    owner: root
    group: root
    mode: 0644

- name: "Change mode of files and certs folder"
  shell:
    cmd: "chmod 755 certs/; sudo chmod 655 certs/*"
    warn: false