---
- name: "Copy docker-compose.yml to server"
  copy:
    src: docker-compose.yml
    dest: /home/robert/docker-compose.yml
    owner: root
    group: root
    mode: 0644

- name: "Deploy containers with docker-compose up"
  shell:
    cmd: "docker-compose up -d"

# change for something that can check the status of the server (some endpoint)
- name: "Wait 30 seconds for Keycloak to start"
  wait_for:
    timeout: 30

- name: "Add SAMBA SSL certificate to cacerts"
  shell:
    cmd: "docker exec -u 0 keycloak_app keytool -import -trustcacerts -file /opt/jboss/keycloak/sambaCert.pem -alias samba.diinf.lan -keystore /usr/lib/jvm/java-11-openjdk-11.0.11.0.9-2.el8_4.x86_64/lib/security/cacerts -storepass changeit -noprompt"
  ignore_errors: true