---
- name: "Check if Pip is already installed"
  command: pip --version
  register: pip_installed
  changed_when: false
  ignore_errors: true

- name: "Install python3-pip package"
  apt:
    name:
      - python3-pip
    state: present
  when: pip_installed is failed