---
version: '3'
 
volumes:
  postgres_data:
      driver: local
 
services:
  postgres:
      image: postgres:13.3
      container_name: postgres_db
      hostname: postgres
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloakPassword
      ports:
        - 5432:5432
  keycloak:
      image: quay.io/keycloak/keycloak:14.0.0
      container_name: keycloak_app
      hostname: keycloak
      restart: unless-stopped
      #volumes:
      #  - /$PWD/sambaCert.pem:/opt/jboss/keycloak/sambaCert.pem
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: keycloakPassword
        KEYCLOAK_USER: administrator
        KEYCLOAK_PASSWORD: P@assw0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 443:8443
      #extra_hosts:
      #  - "samba.diinf.lan:10.128.0.10"
      depends_on:
        - postgres