---
- name: "Find out if {{ id_provider_name }} Provider exists"
  uri:
    url: "{{ keycloak_base_url }}/auth/admin/realms/{{ realm_name }}/identity-provider/instances/{{ id_provider_name }}"
    method: GET
    status_code:
     - 200
     - 404
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
    validate_certs: no
  register: provider_exists
  tags:
    - keycloak_config
    - identity_provider

- name: "Add {{ id_provider_name }} as Identity Provider"
  uri:
    url: "{{ keycloak_base_url }}/auth/admin/realms/{{ realm_name }}/identity-provider/instances"
    method: POST
    src: "{{ id_provider_data_file }}"
    remote_src: "no"
    status_code:
     - 201
    headers:
      Content-type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
    validate_certs: no
  register: keycloak_id_provider_config
  when: provider_exists.status == 404
  tags:
    - keycloak_config
    - identity_provider