---
- name: "Change master realm localization to spanish"
  uri:
    url: "{{ keycloak_base_url }}/auth/admin/realms/master"
    method: PUT
    body_format: json
    body: "{{ master_realm_json }}"
    remote_src: "no"
    status_code:
     - 204
    headers:
      Content-type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
    validate_certs: no
  register: master_realm_update
  tags:
    - keycloak_config

- name: "Find out if Realm {{ keycloak_realm_name }} exists"
  uri:
    url: "{{ keycloak_base_url }}/auth/admin/realms/{{ keycloak_realm_name }}"
    method: GET
    status_code:
     - 200
     - 404
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
    validate_certs: no
  register: realm_exists
  tags:
    - keycloak_config

- name: "Create Realm {{ keycloak_realm_name }}"
  uri:
    url: "{{ keycloak_base_url }}/auth/admin/realms"
    method: POST
    body_format: json
    body: "{{ new_realm_json }}"
    remote_src: "no"
    status_code:
     - 201
    headers:
      Content-type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ keycloak_token.json.access_token }}"
    validate_certs: no
  register: keycloak_realm_create
  when: realm_exists.status == 404
  tags:
    - keycloak_config
