---
- name: "Check if Samba SSL Certificate is already added to cacerts"
  shell:
    cmd: "docker exec -u 0 keycloak_app keytool -list -cacerts -storepass changeit | grep 'samba.diinf.lan'"
  register: cacerts_check
  failed_when: cacerts_check.rc == 2
  changed_when: false

- name: "Copy Samba SSL certificate"
  shell:
    cmd: "openssl s_client -connect {{ samba_server_ip }}:636 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /opt/sistema-centralizado/sambaCert/sambaCert.pem"
  when: cacerts_check.rc == 1

- name: "Add Samba SSL certificate to Java cacerts"
  shell:
    cmd: "docker exec -u 0 keycloak_app keytool -import -trustcacerts -file /opt/jboss/keycloak/sambaCert/sambaCert.pem -alias samba.diinf.lan -cacerts -storepass changeit -noprompt"
  when: cacerts_check.rc == 1