---
- name: "Check if Samba SSL Certificate is already added to cacerts"
  shell:
    cmd: "docker exec -u 0 {{ keycloak_container_name }} keytool -list -cacerts -storepass changeit | grep {{ samba_server_fqdn }}"
  register: cacerts_check
  failed_when: cacerts_check.rc == 2
  changed_when: false
  tags:
    - keycloak_config
    - federation

- name: "Copy Samba SSL certificate"
  shell:
    cmd: "openssl s_client -connect {{ samba_server_fqdn }}:636 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > {{ files_path }}/sambaCert/sambaCert.pem"
  when: cacerts_check.rc == 1
  tags:
    - keycloak_config
    - federation

- name: "Add Samba SSL certificate to Java cacerts"
  shell:
    cmd: "docker exec -u 0 {{ keycloak_container_name }} keytool -import -trustcacerts -file /opt/jboss/keycloak/sambaCert/sambaCert.pem -alias {{ samba_server_fqdn }} -cacerts -storepass changeit -noprompt"
  when: cacerts_check.rc == 1
  tags:
    - keycloak_config
    - federation
