---
- name: "Get OIDC AUTH token from Keycloak"
  include_tasks: get_OIDC_token.yml

- name: "Change localization and add {{ realm_name }} realm"
  include_tasks: config_realms.yml

- name: "Set up User Storage Federation on realm {{ realm_name }}"
  include_tasks: config_federation.yml

- name: "Set up Identity Providers on realm {{ realm_name }}"
  include_tasks: config_id_providers.yml