---
- name: "Update repository index"
  apt:
    update_cache: yes

- name: "Check if Docker is already installed"
  command: docker --version
  register: docker_installed
  changed_when: false
  ignore_errors: true

- name: "Check if Pip is already installed"
  command: pip --version
  register: pip_installed
  changed_when: false
  ignore_errors: true
