---
- name: "Uninstall old Docker versions"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes

- name: "Install Docker packages"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the stable repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: "Install Docker engine"
  apt:
    name:
      - docker-ce={{ docker_ce_version }}
      - docker-ce-cli={{ docker_ce_cli_version }}
      - containerd.io={{ containerd_io_version }}
    state: present
    update_cache: yes

- name: "Unmask, start and enable Docker service"
  systemd:
    name: docker
    masked: no
    state: started
    enabled: yes

- name: "Install Docker Compose"
  get_url: 
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'