---
- name: "Update repository index"
  apt:
    update_cache: yes
  tags:
    - common

- name: "Add the IP address of every hosts to all hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ item }}"
    state: present
  with_items: 
    - "{{ samba_host }}"
    - "{{ keycloak_host }}"
  tags:
    - common
    - host_update

- name: "Create installation directory"
  file:
    path: "{{ files_path }}"
    state: directory
  tags:
    - common
