---
- name: "Update repository & check installed packages"
  include_tasks: checkPackages.yml

- name: "Docker engine installation" 
  include_tasks: dockerInstall.yml
  when: dockerInstalled is failed

- name: "Pip Installation"
  include_tasks: pipInstall.yml
  when: pipInstalled is failed

- name: "Install required Python packages"
  include_tasks: pipPackagesInstall.yml