---
- name: "Uninstall old Docker versions"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes
  tags:
    - docker

- name: "Install Docker packages"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  tags:
    - docker

- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: "Set up the stable repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags:
    - docker

- name: "Install Docker engine"
  apt:
    name:
      - docker-ce={{ docker_ce_version }}
      - docker-ce-cli={{ docker_ce_cli_version }}
      - containerd.io={{ containerd_io_version }}
    state: present
    update_cache: yes
  tags:
    - docker

- name: "Unmask, start and enable Docker service"
  systemd:
    name: docker
    masked: no
    state: started
    enabled: yes
  tags:
    - docker
