---
keycloak_base_url: "https://keycloak.diinf.tk"
keycloak_admin_user: "admin"
keycloak_admin_pass: "Diinf1*"
keycloak_realm_name: "DIINF"
keycloak_realm_data_file: "realm.json"
keycloak_federation_data_file: "federation.json"